// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BilingualController from "./bilingual_controller"
application.register("bilingual", BilingualController)

import CollageController from "./collage_controller"
application.register("collage", CollageController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import RefreshController from "./refresh_controller"
application.register("refresh", RefreshController)
